import type { Metadata } from "next";
import "./globals.css";
import { primaryFont } from "./_fonts/primary";
import Navbar from "@/components/navbar/navbar";
import { ReactLenis } from "@/lib/lenis";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${primaryFont.variable} font-primary`}>
        <ReactLenis root options={{ lerp: 0.085 }}>
          <Navbar />
          {children}
        </ReactLenis>
      </body>
    </html>
  );
}
